<?php
/** @var $block Swarming\SubscribePro\Block\Customer\Widget\Delete */
/** @var $escaper \Magento\Framework\Escaper */
?>
<?php if ($block->isAddressBookEnabled()): ?>
<?php
$addressWidgetUrl = $block->getAddressWidgetUrl();
$addressWidgetJson = $block->getAddressWidgetJson();
?>
<script src="<?php echo $escaper->escapeUrl($addressWidgetUrl); ?>"></script>
<script>
let widgetConfig = <?php echo $addressWidgetJson; ?>;

require([
    'jquery',
], function($){
    let tableContainer = $('#additional-addresses-table'),
        removeBtnList = tableContainer.find('tr a.action.delete');

    if (removeBtnList.length) {
        removeBtnList.on('click', function (e) {
            let self = $(this),
                platformAddress =  {
                    id: self.data('platform-address-id'),
                };

            e.stopPropagation();

            AddressBookAssist.onBeforeAddressDeleted({"address": platformAddress}, function (address, shouldDelete) {
                if (shouldDelete === "delete") {
                    // @see mage.address._deleteAddress
                    if (typeof $(e.target).parent().data('address') !== 'undefined') {
                        window.location = self.options.deleteUrlPrefix + $(e.target).parent().data('address') +
                            '/form_key/' + $.mage.cookies.get('form_key');
                    } else {
                        window.location = self.options.deleteUrlPrefix + $(e.target).data('address') +
                            '/form_key/' + $.mage.cookies.get('form_key');
                    }

                    return true;
                } else {
                    console.log(shouldDelete);
                    return false;
                }
            }).catch((error) => {
                console.error(error);
            });
        });
    }

    let baseWidgetConfig = {
        apiAccessToken: "<?php echo $block->getWidgetAccessTokenForCurrentCustomer(); ?>",
        customerId: <?php echo $block->getPlatformCustomerId(); ?>
    };

    for (let key in baseWidgetConfig) {
        widgetConfig[key] = baseWidgetConfig[key];
    }
    AddressBookAssist.init(widgetConfig);
});
</script>
<div id="sp-address-book"></div>
<?php endif; ?>
